url = "https://books.toscrape.com/"

In [1]:
#importing necessary libraries
import pandas as pd
from bs4 import BeautifulSoup
import requests

In [2]:
#reading the webpage
url = "https://books.toscrape.com/"
response = requests.get(url)
response.status_code

200

In [3]:
#parsing the webpage(only one page)
soup = BeautifulSoup(response.text, "html.parser")

In [4]:
#extracting book details & inserting into df
book_list = []
for book in soup.find_all("li",class_="col-xs-6 col-sm-4 col-md-3 col-lg-3"):
    title = book.find("h3").text
    price = book.find("p",class_="price_color").text
    rating = book.find("p",class_="star-rating")["class"][1]
    availability = book.find("p",class_="instock availability").text.split()[0]
    book = {
        "title": title,
        "price": price,
        "rating": rating,
        "availability": availability
    }
    book_list.append(book)
df_raw = pd.DataFrame(book_list)
df_raw.info()
df_raw.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         20 non-null     object
 1   price         20 non-null     object
 2   rating        20 non-null     object
 3   availability  20 non-null     object
dtypes: object(4)
memory usage: 772.0+ bytes

                          title    price rating availability
0            A Light in the ...  Â£51.77  Three           In
1            Tipping the Velvet  Â£53.74    One           In
2                    Soumission  Â£50.10    One           In
3                 Sharp Objects  Â£47.82   Four           In
4  Sapiens: A Brief History ...  Â£54.23   Five           In

In [5]:
#price is in string format, we need to convert it to float
df_raw["price"] = df_raw["price"].str.replace("Â£", "")
df_raw.info()
df_raw.head()
df_raw["price"] = df_raw["price"].astype(float)
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         20 non-null     object
 1   price         20 non-null     object
 2   rating        20 non-null     object
 3   availability  20 non-null     object
dtypes: object(4)
memory usage: 772.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         20 non-null     object
 1   price         20 non-null     float64
 2   rating        20 non-null     object
 3   availability  20 non-null     object
dtypes: float64(1), object(3)
memory usage: 772.0+ bytes

In [6]:
#rating is in string format, we need to convert it to numeric(eg:"Three" to 3)
import helper_functions as hf
df_raw = hf.convert(df_raw, "rating")
df_raw.info()
df_raw.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         20 non-null     object
 1   price         20 non-null     float64
 2   rating        20 non-null     int64
 3   availability  20 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 772.0+ bytes

c:\Users\akesh\Desktop\Projects\web-scraping-101\books\helper_functions.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[column] = df[column].replace(mapping)

                          title  price  rating availability
0            A Light in the ...  51.77       3           In
1            Tipping the Velvet  53.74       1           In
2                    Soumission  50.10       1           In
3                 Sharp Objects  47.82       4           In
4  Sapiens: A Brief History ...  54.23       5           In

In [7]:
#availability is in string format, we need to convert it to boolean(eg:"In stock" to True)
df_raw = hf.convert_to_boolean(df_raw, "availability")
df_raw.info()
df_raw.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         20 non-null     object
 1   price         20 non-null     float64
 2   rating        20 non-null     int64
 3   availability  20 non-null     bool
dtypes: bool(1), float64(1), int64(1), object(1)
memory usage: 632.0+ bytes

c:\Users\akesh\Desktop\Projects\web-scraping-101\books\helper_functions.py:11: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[column] = df[column].replace(mapping)

                          title  price  rating  availability
0            A Light in the ...  51.77       3          True
1            Tipping the Velvet  53.74       1          True
2                    Soumission  50.10       1          True
3                 Sharp Objects  47.82       4          True
4  Sapiens: A Brief History ...  54.23       5          True

In [8]:
df_processed = df_raw.copy()

In [10]:
df_processed.head()
df_processed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         20 non-null     object
 1   price         20 non-null     float64
 2   rating        20 non-null     int64
 3   availability  20 non-null     bool
dtypes: bool(1), float64(1), int64(1), object(1)
memory usage: 632.0+ bytes